In [46]:
# Artificial Neural Network
import numpy as np
import pandas as pd
import tensorflow as tf
from pandas import Series,DataFrame
from pandas import Series,DataFrame
import seaborn as sns



In [47]:
from keras.callbacks import ModelCheckpoint
from keras.models import load_model

In [48]:
tf.__version__

'2.13.0'

Importing the dataset

In [49]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [50]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [51]:
print(y)

[1 0 1 ... 1 1 0]


In [52]:
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [53]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [55]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [56]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [57]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [58]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

# Adding layers

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [62]:
# Compiling the ANN
ann.compile( optimizer = 'adam',loss = 'binary_crossentropy')

In [63]:
filename = 'ann.h5'
checkpoint = ModelCheckpoint(filename,save_best_only=True)
ann.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=32, epochs=100, callbacks=[checkpoint])
#ann.fit(X_train, y_train,validation_data=(X_test, y_test), batch_size = 32, epochs = 100,callbacks=[checkpoint])

Epoch 1/100
250/250 [==============================] - 5s 8ms/step - loss: 0.3950 - val_loss: 0.3900
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3837 - val_loss: 0.3807
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3754 - val_loss: 0.3730
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3688 - val_loss: 0.3654
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3631 - val_loss: 0.3599
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3585 - val_loss: 0.3562
Epoch 7/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3549 - val_loss: 0.3511
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3515 - val_loss: 0.3482
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3493 - val_loss: 0.3466
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3470 - val_lo

250/250 [==============================] - 1s 5ms/step - loss: 0.3294 - val_loss: 0.3290
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3295 - val_loss: 0.3290
Epoch 83/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3294 - val_loss: 0.3289
Epoch 84/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3295 - val_loss: 0.3320
Epoch 85/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3295 - val_loss: 0.3287
Epoch 86/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3293 - val_loss: 0.3288
Epoch 87/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3289 - val_loss: 0.3296
Epoch 88/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3292 - val_loss: 0.3296
Epoch 89/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3293 - val_loss: 0.3281
Epoch 90/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3292 - val_loss: 

In [36]:
# Training the ANN on the Training set
#ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

### Predicting the result of a single observation

pred 1

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

In [26]:
x=(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
x=x*100
print('probability of customer leaving:', x)

1/1 [==============================] - 0s 32ms/step
probability of customer leaving: [[2.647432]]


pred 1

Geography: Germany

Credit Score: 200

Gender: Male

Age: 60 years old

Tenure: 1 years

Balance: $ 30000

Number of Products: 1

Does this customer have a credit card ? no

Is this customer an Active Member: no

Estimated Salary: \$ 50000

In [35]:
x=ann.predict(sc.transform([[0, 1, 0, 200, 1, 60, 1, 30000, 1, 0, 0,  50000]]))
x=x*100
print('probability of customer leaving:',x,'%')

1/1 [==============================] - 0s 29ms/step
probability of customer leaving: [[86.04476]] %


In [39]:
model = load_model('ann.h5')
x=model.predict(sc.transform([[0, 1, 0, 200, 1, 60, 1, 30000, 1, 0, 0,  50000]]))
x=x*100
print('probability of customer leaving:',x,'%')

1/1 [==============================] - 0s 78ms/step
probability of customer leaving: [[86.04476]] %


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred)

0.8605